### ISSUE TITLE
json文件中的“721”文件问题

### ISSUE THREAD

**Issue by SunnyCc123** [liyichen-cly/MSNEA#11]
你好，我是知识图谱领域的小白，最近在研究多模态实体对齐相关工作，想请问一下config.json里面的"dataset_division": "721"，721这个文件夹应该怎样获取呢？非常期待您的解答！

**Comment by liyichen-cly** [comment]
Hi! Please divide this file into proportions of 70%, 20%, and 10% respectively. https://github.com/mniepert/mmkb/blob/master/DB15K/DB15K_SameAsLink.txt

**Comment by SunnyCc123** [comment]
非常感谢！

**Comment by SunnyCc123** [comment]
作者您好！还想请问一下，为了对应您论文里对齐种子是20%,50%,80%的情况，我应该将721文件里训练集分别按照20%，50%，80%进行分割吗？那么对应的验证集和测试集分别按照什么比例进行划分呐？非常期待您的回复！

**Comment by liyichen-cly** [comment]
您好！分别是：1.训练集20%，测试集70%，验证集10%；2.训练集50%，测试集40%，验证集10%；3.训练集80%，测试集10%，验证集10%。另外，我们正在尝试恢复服务器上的数据，恢复完成后将数据集尽快开源。

**Comment by SunnyCc123** [comment]
好的明白！非常感谢您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月26日(星期五) 下午4:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [liyichen-cly/MSNEA] json文件中的“721”文件问题 (Issue #11)














 
您好！分别是：1.训练集20%，测试集70%，验证集10%；2.训练集50%，测试集40%，验证集10%；3.训练集80%，测试集10%，验证集10%。另外，我们正在尝试恢复服务器上的数据，恢复完成后将数据集尽快开源。
