### ISSUE TITLE
where is the pre-extracted image embeddings?

### ISSUE THREAD

**Issue by xue19890510** [liyichen-cly/MSNEA#2]
Thank you for your work
 I am looking for the dataset that used in your paper,   the code 
        self.id_ent_images_res_dict1 = self.read_image_resnet(data_folder + 'resnet50_1.h5', self.ent_ids1_dict)
        self.id_ent_images_res_dict2 = self.read_image_resnet(data_folder + 'resnet50_2.h5', self.ent_ids2_dict)
I can't find resnet50_1.h5  resnet50_2.h5  in the  link  https://github.com/mniepert/mmkb, the project mmkb only gives VGG16 extracted data.
So, could you show me how to get  resnet50_1.h5 and resnet50_2.h5

**Comment by mqEpiphany** [comment]
请问你找到了吗

**Comment by liyichen-cly** [comment]
I have already provided the processing codes in the issues #9, 10.
