### ISSUE TITLE
数据相关问题

### ISSUE THREAD

**Issue by MathscrG** [liyichen-cly/MSNEA#4]
你好，感谢您的工作，但是从MMKG那里下载过来的数据集貌似是经过处理后才进行训练的，如果是这样的话，能否上传一下处理的代码或者处理后的数据呢？

**Comment by NaturalzzZ** [comment]
> 你好，感谢您的工作，但是从MMKG那里下载过来的数据集貌似是经过处理后才进行训练的，如果是这样的话，能否上传一下处理的代码或者处理后的数据呢？
想问一下解决了吗

**Comment by MathscrG** [comment]
没有解决呢，发邮件也没有答复，建议不要follow了

**Comment by liyichen-cly** [comment]
I have already provided the processing codes in the issues #9, 10.
