### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by PrimaLuz** [liyichen-cly/MSNEA#6]
你好，我发现代码需要的数据是需要经过预处理的，请问可否提供数据集处理的代码或者处理后数据的内容样式吗

**Comment by NaturalzzZ** [comment]
> 你好，我发现代码需要的数据是需要经过预处理的，请问可否提供数据集处理的代码或者处理后数据的内容样式吗

想问一下解决了吗！

**Comment by liyichen-cly** [comment]
I have already provided the processing codes in the issues #9, 10.
