### ISSUE TITLE
Missing Dataset

### ISSUE THREAD

**Issue by usmananjum** [liyichen-cly/MSNEA#8]
I have been trying to run your code but the dataset is not provided. The download link provided for the dataset does not work, e.g. in KGs class, the data folder should contain rel_triples_1 & rel_triples_2, resnet50_1.h5, attr_triples_1, attr_name_1.h5, etc. - where can I find these files?

**Comment by NaturalzzZ** [comment]
> I have been trying to run your code but the dataset is not provided. The download link provided for the dataset does not work, e.g. in KGs class, the data folder should contain rel_triples_1 & rel_triples_2, resnet50_1.h5, attr_triples_1, attr_name_1.h5, etc. - where can I find these files?
I'd like to ask if you've solved the problem yet?

**Comment by liyichen-cly** [comment]
I have already provided the processing codes in the issues #9, 10. The triplet data is available in the link.
